# Prometheus configuration for MCP RAG Server
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mcp-rag-monitor'

# Rules files
rule_files:
  - "alert_rules.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # MCP Server metrics
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # RAG Engine metrics
  - job_name: 'rag-engine'
    static_configs:
      - targets: ['rag-engine:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Sync Service metrics
  - job_name: 'sync-service'
    static_configs:
      - targets: ['sync-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Accessibility Service metrics
  - job_name: 'accessibility-service'
    static_configs:
      - targets: ['accessibility-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Custom application metrics with relabeling
  - job_name: 'mcp-rag-custom'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/api/v1/metrics'
    scrape_interval: 15s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'mcp_rag_(.*)'
        target_label: __name__
        replacement: '${1}'

# Remote write (for production - optional)
# remote_write:
#   - url: "https://prometheus-us-central1.grafana.net/api/prom/push"
#     basic_auth:
#       username: "your_username"
#       password: "your_api_key"